--File: game_journal_english_i3.lua

function p.main()
    game_journal_english_i3_aladdin_cave.main()
    game_journal_english_i3_basement_lib.main()
    game_journal_english_i3_black_mushroom.main()
    game_journal_english_i3_cellar_lib.main()
    game_journal_english_i3_colchester.main()
    game_journal_english_i3_desert_cactus.main()
    game_journal_english_i3_desert_flower.main()
    game_journal_english_i3_desert_top.main()
    game_journal_english_i3_forest_museum.main()
    game_journal_english_i3_hard_orange_flower.main()
    game_journal_english_i3_jackfruit.main()
    game_journal_english_i3_lib.main()
    game_journal_english_i3_lib_lib.main()
    game_journal_english_i3_mahogany.main()
    game_journal_english_i3_red_maze_flower.main()
    game_journal_english_i3_river.main()
    game_journal_english_i3_salmon_mushroom.main()
    game_journal_english_i3_sliver_maze.main()
    game_journal_english_i3_starksboro.main()
    game_journal_english_i3_tangerine.main()
    game_journal_english_i3_treetop.main()
    game_journal_english_i3_treetop_inner.main()
    game_journal_english_i3_weapon_lib.main()
    game_journal_english_i3_yellow_mushroom.main()
    --more!!!
end
