--File: game_journal_english_i2.lua

function p.main()
    game_journal_english_i2_blue_mushroom.main()
    game_journal_english_i2_bubble_cave.main()
    game_journal_english_i2_creeping_jeni.main()
    game_journal_english_i2_danville.main()
    game_journal_english_i2_emp_city.main()
    game_journal_english_i2_fanatic_blue.main()
    game_journal_english_i2_fanatic_island.main()
    game_journal_english_i2_fanatic_spire.main()
    game_journal_english_i2_fanatic_weed.main()
    game_journal_english_i2_laser_branch_vine.main()
    game_journal_english_i2_lib.main()
    game_journal_english_i2_montreal.main()
    game_journal_english_i2_mountains.main()
    game_journal_english_i2_mystic_vine.main()
    game_journal_english_i2_pink_puzzle.main()
    game_journal_english_i2_rad_caves.main()
    game_journal_english_i2_raspberry.main()
    game_journal_english_i2_scorpius_flower.main()
    game_journal_english_i2_small_blue_flower.main()
    game_journal_english_i2_spruce_tree.main()
    game_journal_english_i2_toronto.main()
    game_journal_english_i2_toronto_maze.main()
    game_journal_english_i2_violets.main()
    game_journal_english_i2_weed_rings.main()
    game_journal_english_i2_wig_checkpoint.main()
    --more!!!
end
