function p.func1() return "foo" end
function p.func2() return 13 end

function p.main()
    -- local type = ga_get_type("xar.stats.kill_count")
    -- local type = ga_dyn_get_var_type("dyn.base.waypoint.2.name")
    -- ga_print("aaa_check_api: type = " .. type)

    -- ga_package_set_b("protected.can_use_named_pipes", false)
    -- ga_package_set_b("test_b", false)

    -- ga_dump_lua_env()

    -- ga_print("Here in aaa_check_api:")
    -- local list = ga_get_current_packages()
    -- for _,v in ipairs(list) do
    --     ga_print("using package: " .. v.name)
    -- end

    -- ga_print("Here in aaa_check_api.lua")
    -- local texs = ga_get_tex_names_with_prefix("ammo")
    -- for k,v in ipairs(texs) do
    --     ga_print("found texture: " .. tostring(v.name))
    -- end

    -- ga_print("aaa the time = " .. tostring(ga_get_sys_time()))

    -- ga_dyn_set_i("dyn.foo", 12)
    -- ga_exit()

    -- ga_print("In aaa_chunk_api: ")

    -- local temp = ( p.func1() < p.func2() )

    -- ga_command("foo")
    -- ga_save(true)
    -- ga_load()
    -- ga_exit()
    -- ga_exit_error()
    -- ga_print("hello")
    -- ga_flush()
    -- ga_console_print("hello")
    -- ga_dump_lua_env()

    -- ga_return_b("sdf", true)

    -- ga_get_game_time()
    -- ga_get_level_time(12)

    -- ga_srand(12)
    -- ga_rand()
    -- ga_randf()
    -- ga_randf_range(1.0, 2.0)
    -- ga_randi(1,2)

    -- ga_exists("foo")
    -- ga_create_b("foo")
    -- ga_create_i("foo")
    -- ga_create_f("foo")
    -- ga_create_s("foo")
    -- ga_create_v("foo")
    -- ga_init_b("foo", true)
    -- ga_init_i("foo", 12)
    -- ga_init_f("foo", 2.0)
    -- ga_init_s("foo", "bar")
    -- ga_init_v("foo", std.vec(1,2,3))
    -- ga_get_b("foo")
    -- ga_get_i("foo")
    -- ga_get_f("foo")
    -- ga_get_s("foo")
    -- ga_get_v("foo")
    -- ga_set_b("foo", true)
    -- ga_set_i("foo", 12)
    -- ga_set_f("foo", 3.14)
    -- ga_set_s("foo", "bar")
    -- ga_set_v("foo", std.vec(1,2,3))
    -- ga_toggle_b("foo")
    -- ga_get_sys_b("foo")
    -- ga_get_sys_i("foo")
    -- ga_get_sys_f("foo")
    -- ga_get_sys_s("foo")
    -- ga_get_sys_v("foo")
    -- ga_set_sys_b("foo", true)
    -- ga_set_sys_i("foo", 12)
    -- ga_set_sys_f("foo", 3.14)
    -- ga_set_sys_v("foo", std.vec(1,2,3))
    -- ga_set_sys_s("foo", "bar")
    -- ga_package_init_b("foo", true)
    -- ga_package_get_b("foo")
    -- ga_package_set_b("dingle", true)

    ---------------------------------------------

    -- ga_package_init_b("test_b", true)
    -- ga_package_init_i("test_i", 42)
    -- ga_package_init_f("test_f", 3.14)
    -- ga_package_init_v("test_v", std.vec(1,2,3))
    -- ga_package_init_s("test_s", "example")

    -- ga_package_set_b("test_b", false)
    -- ga_package_set_i("test_i", 56)
    -- ga_package_set_f("test_f", 5.12)
    -- ga_package_set_v("test_v", std.vec(4,5,6))
    -- ga_package_set_s("test_s", "example2")

    -- ga_print("Printing package vars:")
    -- ga_print( tostring(ga_package_get_b("test_b")) )
    -- ga_print( tostring(ga_package_get_i("test_i")) )
    -- ga_print( tostring(ga_package_get_f("test_f")) )
    -- ga_print( std.vec_to_str(ga_package_get_v("test_v")) )
    -- ga_print( tostring(ga_package_get_s("test_s")) )

    -- ga_package_var_remove("test_b")
    -- ga_package_var_remove("test_i")
    -- ga_package_var_remove("test_f")
    -- ga_package_var_remove("test_v")
    -- ga_package_var_remove("test_s")

    ---------------------------------------------

    -- local other_package = "foo"
    -- ga_package2_init_b(other_package, "test_b", true)
    -- ga_package2_init_i(other_package, "test_i", 42)
    -- ga_package2_init_f(other_package, "test_f", 3.14)
    -- ga_package2_init_v(other_package, "test_v", std.vec(1,2,3))
    -- ga_package2_init_s(other_package, "test_s", "example")

    -- ga_package2_set_b(other_package, "test_b", true)
    -- ga_package2_set_i(other_package, "test_i", 74)
    -- ga_package2_set_f(other_package, "test_f", 6.13)
    -- ga_package2_set_v(other_package, "test_v", std.vec(7,8,9))
    -- ga_package2_set_s(other_package, "test_s", "example3")

    -- ga_print("Printing other package vars:")
    -- ga_print( tostring(ga_package2_get_b(other_package, "test_b")) )
    -- ga_print( tostring(ga_package2_get_i(other_package, "test_i")) )
    -- ga_print( tostring(ga_package2_get_f(other_package, "test_f")) )
    -- ga_print( std.vec_to_str(ga_package2_get_v(other_package, "test_v")) )
    -- ga_print( tostring(ga_package2_get_s(other_package, "test_s")) )

    -- ga_package2_var_remove(other_package, "test_b")
    -- ga_package2_var_remove(other_package, "test_i")
    -- ga_package2_var_remove(other_package, "test_f")
    -- ga_package2_var_remove(other_package, "test_v")
    -- ga_package2_var_remove(other_package, "test_s")

    ---------------------------------------------

    -- ga_dyn_exists("foo")
    -- ga_dyn_create_b("dyn.foo")
    -- ga_dyn_create_i("dyn.foo")
    -- ga_dyn_create_f("dyn.foo")
    -- ga_dyn_create_v("dyn.foo")
    -- ga_dyn_create_s("dyn.foo")
    -- ga_dyn_init_b("dyn.foo", true)
    -- ga_dyn_init_i("dyn.foo", 12)
    -- ga_dyn_init_f("dyn.foo", 3.14)
    -- ga_dyn_init_v("dyn.foo", std.vec(1,2,3))
    -- ga_dyn_init_s("dyn.foo", "bar")
    -- ga_dyn_get_b("foo")
    -- ga_dyn_get_i("foo")
    -- ga_dyn_get_f("foo")
    -- ga_dyn_get_v("foo")
    -- ga_dyn_get_s("foo")
    -- ga_dyn_set_b("foo", true)
    -- ga_dyn_set_i("foo", 12)
    -- ga_dyn_set_f("foo", 3.14)
    -- ga_dyn_set_v("foo", std.vec(1,2,3))
    -- ga_dyn_set_s("foo", "bar")
    -- ga_dyn_remove("foo")
    -- ga_dyn_node_itr_start("foo")
    -- ga_dyn_node_itr_next()
    -- ga_dyn_leaf_itr_start("foo")
    -- ga_dyn_leaf_itr_next()
    -- ga_dyn_dump()

    -- ga_play_sound("foo")
    -- ga_play_sound_menu("foo")
    -- ga_play_music("foo")
    -- ga_stop_music()

    -- ga_genesis()
    -- ga_kill_player()
    -- ga_use_object_exists()

    -- ga_hud_msg("foo", 3.14)
    -- ga_hud_reg_damage_from_dir(42, std.vec(1,2,3))
    -- ga_hud_reg_damage_from_dir_color(42, std.vec(1,2,3), std.vec(1,2,3))
    -- ga_hud_reg_dir_tex("foo", "bar", std.vec(1,2,3), 3.14)

    -- ga_shrink()
    -- ga_shrink2(std.vec(1,2,3))
    -- ga_grow()
    -- ga_grow2(std.vec(1,2,3))
    -- ga_tele("333", std.vec(1,2,3))
    -- ga_tele_pink()
    -- ga_tele_pink2(std.vec(1,2,3))
    -- ga_tele_blue()
    -- ga_tele_blue2(std.vec(1,2,3))
    -- ga_tele_same_level(std.vec(1,2,3))

    -- ga_window_push("foo")
    -- ga_window_pop()
    -- ga_window_pop_all()
    -- ga_window_push("foo")
    -- ga_hud_window_add("foo", 12)
    -- ga_hud_window_remove("foo")

    -- ga_get_viewer_chunk_id()
    -- ga_get_viewer_level()
    -- ga_get_viewer_offset()
    -- ga_get_viewer_lp(42)
    -- ga_get_viewer_bp(42)
    -- ga_get_viewer_path()
    -- ga_get_viewer_path_ext()
    -- ga_get_vec_to_viewer(42, std.vec(1,2,3))
    -- ga_lbp_dist_to_viewer(5, 12)
    -- ga_block_dist_to_viewer(42, std.bp(1,2,3))
    -- ga_ment_get_var_special_vec_to_viewer(5)
    -- ga_ment_get_var_special_dist_to_viewer(5)

    -- ga_bent_get_type(42, std.bp(1,2,3))
    -- ga_bent_add(42, std.bp(1,2,3), "foo", 100.0)
    -- ga_bent_add_i(42, std.bp(1,2,3), "foo", 12, 100.0)
    -- ga_bent_add_s(42, std.bp(1,2,3), "foo", "bar", 100.0)
    -- ga_bent_set_param_i(42, std.bp(1,2,3), 12, 100.0)
    -- ga_bent_set_param_s(42, std.bp(1,2,3), "bar", 100.0)
    -- ga_bent_get_param_s(42, std.bp(1,2,3))
    -- ga_bent_get_param_i(42, std.bp(1,2,3))
    -- ga_bent_remove_temp(42, std.bp(1,2,3), 12)
    -- ga_bent_remove_perm(42, std.bp(1,2,3))
    -- ga_bent_sphere_query(42, std.vec(1,2,3), 3.14)

    -- ga_ment_type_var_exists("foo", "var")
    -- ga_ment_get_static_b("foo", "var")
    -- ga_ment_get_static_i("foo", "var")
    -- ga_ment_get_static_f("foo", "var")
    -- ga_ment_get_static_v("foo", "var")
    -- ga_ment_get_static_s("foo", "var")
    -- ga_ment_static_b_exists_and_true("foo", "var")

    -- ga_ment_start(42, std.vec(1,2,3), "ment_type")
    -- ga_ment_end()
    -- ga_ment_init_set_b("var", true)
    -- ga_ment_init_set_i("var", 12)
    -- ga_ment_init_set_f("var", 3.14)
    -- ga_ment_init_set_v("var", std.vec(1,2,3))
    -- ga_ment_init_set_s("var", "foo")
    -- ga_ment_var_exists(4000, "var")
    -- ga_ment_get_b(4000, "var")
    -- ga_ment_get_i(4000, "var")
    -- ga_ment_get_f(4000, "var")
    -- ga_ment_get_v(4000, "var")
    -- ga_ment_get_s(4000, "var")
    -- ga_ment_b_exists_and_true(4000, "var")
    -- ga_ment_set_var_rt_only(4000, "var", 12)
    -- ga_ment_set_b(4000, "var", true)
    -- ga_ment_set_i(4000, "var", 12)
    -- ga_ment_set_f(4000, "var", 3.14)
    -- ga_ment_set_v(4000, "var", std.vec(1,2,3))
    -- ga_ment_set_s(4000, "var", "bar")
    -- ga_ment_inst_id_to_code_id(4000)
    -- ga_ment_code_id_to_inst_id(4000)
    -- ga_ment_exists(4000)
    -- ga_ment_remove(4000)
    -- ga_ment_get_type(4000)
    -- ga_ment_get_lp(4000)
    -- ga_ment_get_sllp(4000)
    -- ga_ment_get_level(4000)
    -- ga_ment_dump(4000)
    -- ga_ment_sphere_query(42, 42, 42, std.vec(1,2,3), 3.14)
    -- ga_ment_set_alarm(4000, 100.0, "alarm");
    -- ga_ment_set_alarm_on_level(4000, 42, 100.0, "alarm")
    -- ga_ment_all_dump()

    -- -- I trust these.
    -- ga_particle_add()
    -- ga_particle_explosion()
    -- ga_particle_trail()
    -- ga_particle_ring()

    -- ga_lbp_seed_pos(42,12)
    -- ga_block_seed_pos(42, std.bp(1,2,3))
    -- ga_block_get(42, std.bp(1,2,3))
    -- ga_get_cocoon_block_of_chunk(42, std.bp(1,2,3))
    -- ga_block_change_rl(42, std.bp(1,2,3), "grass", 100.0)
    -- ga_block_change_rl_default(42, std.bp(1,2,3), "grass")
    -- ga_block_change_perm(42, std.bp(1,2,3), "grass")
    -- ga_block_get_b(42, std.bp(1,2,3), "var")
    -- ga_block_get_i(42, std.bp(1,2,3), "var")
    -- ga_block_get_f(42, std.bp(1,2,3), "var")
    -- ga_block_get_v(42, std.bp(1,2,3), "var")
    -- ga_block_get_s(42, std.bp(1,2,3), "var")
    -- ga_block_set_b(42, std.bp(1,2,3), "var", true)
    -- ga_block_set_i(42, std.bp(1,2,3), "var", 12)
    -- ga_block_set_f(42, std.bp(1,2,3), "var", 3.14)
    -- ga_block_set_v(42, std.bp(1,2,3), "var", std.vec(1,2,3))
    -- ga_block_set_s(42, std.bp(1,2,3), "var", "bar")
    -- ga_bt_get_physically_solid("grass")

    -- ga_set_respawn_point("EMPTY_PATH", std.bp(1,2,3))

    -- ga_chunk_id_to_level(4000)
    -- ga_chunk_id_to_vcp(4000)
    -- ga_chunk_id_to_path(4000)
    -- ga_vcp_to_chunk_id(100, std.bp(1,2,3))
    -- ga_path_to_chunk_id("EMPTY_PATH")
    -- ga_level_scale_factor(12,13)
    -- ga_convert_lp(12,13, std.vec(1,2,3))
    -- ga_vcp_to_parent_bp(10, std.bp(1,2,3))
    -- ga_bp_to_path(12, std.bp(1,2,3))
    -- ga_bp_to_parent_bp(12, std.bp(1,2,3))

    -- ga_path_diff("EMPTY_PATH", "EMPTY_PATH")

    -- ga_move_set_desired_travel(std.vec(1,2,3))
    -- ga_move_set_spin(3.14)
    -- ga_move_get_on_sure_footing()
    -- ga_move_set_ledge_guards(true)
    -- ga_move_set_body_spirit()
    -- ga_move_set_body_ground(std.vec(1,2,3), 3.14, 10.0, 5.0)
    -- ga_move_set_body_fly(std.vec(1,2,3), 3.14, false)
    -- ga_player_model_set_look()
    -- ga_player_model_q2md2_set_cmd("foo")
    -- ga_player_model_q2md2_set_state("bar")

    -- ga_vis_test_level(12, std.vec(1,2,3), std.vec(1,2,3))

    -- --It complains about a null pointer.
    -- ga_reboot_dyn_itr_get()
    -- ga_reboot_dyn_itr_next()
    -- ga_reboot_dyn_itr_at_end()
    -- ga_reboot_dyn_itr_save()

    -- ga_debug1()
    -- ga_debug2()
end
